language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script: "make install-dependencies-dev"

script:
  - "make tests"
  - "make code-sniffer-cli"

notifications:
  irc: "irc.freenode.org#environaut"
